### ISSUE TITLE
?quote permissions are no good

### ISSUE THREAD

**Issue by synixebrett** [Synixe/Bot#52]

**Comment by namelessOwO** [comment]
Hello, this is nameless, 
Synixe & Co are well aware of this error and a hotfix is being released shortly.
This error was caused by the lack of our QA team (brett) falling asleep on the job.

He has been recently fired (brett), and replaced by Norkeys.

Thank you for your kind understanding and have a great day in these dark times of dictatorship.

Helping you help yourself,
NamelessOwO
Helper
